//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Rs.NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public System.Guid IdPedido { get; set; }
        public System.Guid IdUsuario { get; set; }
        public Nullable<System.DateTime> FechPedido { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public Nullable<int> EstadoPedido { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> IdDeliveryPrecio { get; set; }
    
        public virtual DELIVERYPRECIO DELIVERYPRECIO { get; set; }
        public virtual TIPOPAGO TIPOPAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PEDIDODETALLE PEDIDODETALLE { get; set; }
    }
}
