//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Rs.NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDODETALLE
    {
        public System.Guid IdPedido { get; set; }
        public System.Guid IdProducto { get; set; }
        public Nullable<decimal> CantProducto { get; set; }
        public Nullable<decimal> PrecProducto { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
