//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Rs.NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.PEDIDODETALLE = new HashSet<PEDIDODETALLE>();
        }
    
        public System.Guid IdProducto { get; set; }
        public string DescProducto { get; set; }
        public Nullable<decimal> PrecProducto { get; set; }
        public Nullable<bool> EstadoProducto { get; set; }
        public Nullable<int> IdTipoProducto { get; set; }
        public byte[] IMGProducto { get; set; }
        public string ProductoFileName { get; set; }
        public Nullable<System.Guid> IdTienda { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDODETALLE> PEDIDODETALLE { get; set; }
        public virtual TIENDAS TIENDAS { get; set; }
        public virtual TIPOSPRODUCTO TIPOSPRODUCTO { get; set; }
    }
}
