//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Rs.NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIENDAS()
        {
            this.BANNER = new HashSet<BANNER>();
            this.PRODUCTOS = new HashSet<PRODUCTOS>();
        }
    
        public System.Guid IdTienda { get; set; }
        public string DescTienda { get; set; }
        public string DirecTienda { get; set; }
        public Nullable<int> TelefTienda { get; set; }
        public string CorreoTienda { get; set; }
        public Nullable<bool> EstadoTienda { get; set; }
        public Nullable<System.Guid> IdCiudad { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BANNER> BANNER { get; set; }
        public virtual CIUDAD CIUDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOS> PRODUCTOS { get; set; }
    }
}
