//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models.Rs.NEW
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.DIRECUSUARIO = new HashSet<DIRECUSUARIO>();
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public System.Guid IdUsuario { get; set; }
        public string NomUsuario { get; set; }
        public string ApeUsuario { get; set; }
        public Nullable<int> DNIUsuario { get; set; }
        public Nullable<int> TelefUsuario { get; set; }
        public string CorreoUsuario { get; set; }
        public Nullable<bool> EstadoUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIRECUSUARIO> DIRECUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO { get; set; }
    }
}
